### ISSUE TITLE
ECONNREFUSED error

### ISSUE THREAD

**Issue by jshakes** [openfin/node-openfin-launcher#33]
When trying to launch the Hyperblotter demo, I get an error from this package:

`TypeError: Cannot read property 'setEncoding' of undefined` from `asset-fetcher.js:29:17`

When I logged out the value of `response` I got:

```
{ Error: connect ECONNREFUSED 127.0.0.1:5001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5001 }
```

Any ideas why I get this error from 127.0.0.1:5001? What is meant to be running there?

**Comment by dcchuck** [comment]
When building & running the demo, you're ->

1) Launching a local web server on port 5001
2) Using the openfin-launcher to target the locally hosted site/app.json

Looks like you're unable to connect to port 5001. Is there any reason you can't run on localhost?
